#
# r | art
#

```{r}
library(tidyverse)
```

# circle

```{r}
seq(0, 1, .01) %>%
data.frame(a=.) %>%
ggplot(aes(x=a, y=0)) +
geom_point(alpha=.2, color="#000000", size=0) +
coord_polar() +
theme_void()
```

# flower | rose

```{r}
seq(-pi, pi, .01) %>%
data.frame(a=.) %>%
ggplot(aes(x=a, y=2*sin(4*a))) +
geom_point(alpha=.2, color="#000000", size=0) +
coord_polar() +
theme_void()
```

# flower | rose #2

```{r}
seq(-2*pi, 2*pi, .01) %>%
data.frame(a=.) %>%
ggplot(aes(x=a, y=cos(3*a))) +
geom_point(alpha=.2, color="#000000", size=0) +
coord_polar() +
theme_void()
```

# golden flower

```{r}
golden_ratio <- (1+sqrt(5))/2
golden_angle <- pi*(3-sqrt(5))

(seq(0, 1000, .02) * golden_angle) %>%
data.frame(a=., x=sin(.), y=cos(.)) %>%
ggplot(aes(x=a*x, y=a*y)) +
geom_point(aes(color=a), alpha=.4, size=0, shape=".", show.legend=F) +
scale_color_gradientn(colors = c("#554e41", "#c3ad95", "#eba584", "#d4a67c")) +
theme_void()
```

# <3

```{r}

# shape (201, 1) -> (40401, 2)

seq(-1, 1, .01) %>%
expand.grid(x=., y=.) %>%
ggplot(aes(x=pi*x-cos(y^2), y=1-sin(x^2))) +
geom_point(alpha=.02, color="#000000", size=0) +
coord_polar() +
theme_void()
```

# save

```{r}
t <- format(Sys.time(), format="%F_%H-%M")
fn <- paste(t, "png", sep=".")
ggsave(fn, units="in", width=1800/300, height=1800/300)
```
